export const CAR_BRANDS = [
  "Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Bugatti", "Buick", 
  "BYD", "Cadillac", "Chevrolet", "Chrysler", "Citroën", "Dacia", "Dodge", "Ferrari", 
  "Fiat", "Ford", "Genesis", "GMC", "Honda", "Hyundai", "Infiniti", "Jaguar", "Jeep", 
  "Kia", "Koenigsegg", "Lamborghini", "Land Rover", "Lexus", "Lincoln", "Lotus", 
  "Lucid", "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "MINI", "Mitsubishi", 
  "Nissan", "Pagani", "Peugeot", "Polestar", "Porsche", "Ram", "Renault", "Rivian", 
  "Rolls-Royce", "Seat", "Skoda", "Smart", "Subaru", "Suzuki", "Tesla", "Toyota", 
  "Volkswagen", "Volvo"
];

export const CAR_MODELS: Record<string, string[]> = {
  "Acura": ["ILX", "MDX", "NSX", "RDX", "TLX", "Integra"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C", "Giulietta"],
  "Aston Martin": ["DB11", "DBS", "DBX", "Vantage", "Vanquish"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "R8", "RS3", "RS4", "RS5", "RS6", "RS7", "RSQ8"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur"],
  "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "i7", "iX", "M2", "M3", "M4", "M5", "M8"],
  "Bugatti": ["Chiron", "Veyron", "Divo"],
  "Buick": ["Enclave", "Encore", "Envision", "LaCrosse", "Regal"],
  "BYD": ["Atto 3", "Han", "Tang", "Dolphin", "Seal", "Song"],
  "Cadillac": ["CT4", "CT5", "CT6", "Escalade", "LYRIQ", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Blazer", "Camaro", "Colorado", "Corvette", "Equinox", "Malibu", "Silverado", "Suburban", "Tahoe", "Traverse", "Trax", "Bolt EV"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5 Aircross", "Berlingo"],
  "Dacia": ["Duster", "Sandero", "Logan", "Jogger", "Spring"],
  "Dodge": ["Challenger", "Charger", "Durango", "Hornet", "Ram 1500 (Legacy)"],
  "Ferrari": ["488", "812 Superfast", "F8 Tributo", "Portofino", "Roma", "SF90 Stradale", "Purosangue", "LaFerrari"],
  "Fiat": ["500", "500X", "Panda", "Tipo", "Punto"],
  "Ford": ["Bronco", "Edge", "Escape", "Expedition", "Explorer", "F-150", "F-250", "Fiesta", "Focus", "Mustang", "Mustang Mach-E", "Ranger", "Transit", "Puma", "Kuga"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GMC": ["Acadia", "Canyon", "Hummer EV", "Sierra 1500", "Terrain", "Yukon"],
  "Honda": ["Accord", "Civic", "CR-V", "HR-V", "Insight", "Odyssey", "Passport", "Pilot", "Ridgeline", "Jazz/Fit"],
  "Hyundai": ["Elantra", "Ioniq 5", "Ioniq 6", "Kona", "Palisade", "Santa Fe", "Sonata", "Tucson", "Venue", "i10", "i20", "i30"],
  "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  "Jaguar": ["E-PACE", "F-PACE", "F-TYPE", "I-PACE", "XE", "XF"],
  "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler", "Avenger"],
  "Kia": ["EV6", "Forte", "Niro", "Rio", "Seltos", "Sorento", "Soul", "Sportage", "Stinger", "Telluride", "Picanto", "Ceed"],
  "Koenigsegg": ["Jesko", "Gemera", "Regera"],
  "Lamborghini": ["Aventador", "Huracán", "Urus", "Revuelto"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus": ["ES", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "UX"],
  "Lincoln": ["Aviator", "Corsair", "Nautilus", "Navigator"],
  "Lotus": ["Emira", "Evija", "Eletre"],
  "Lucid": ["Air"],
  "Maserati": ["Grecale", "Ghibli", "Levante", "Quattroporte", "MC20"],
  "Mazda": ["CX-30", "CX-5", "CX-50", "CX-9", "CX-90", "Mazda3", "Mazda6", "MX-5 Miata", "MX-30"],
  "McLaren": ["720S", "750S", "765LT", "Artura", "GT", "P1"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "S-Class", "SL", "AMG GT"],
  "MINI": ["Clubman", "Countryman", "Hardtop", "Convertible"],
  "Mitsubishi": ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport", "Pajero", "L200"],
  "Nissan": ["Altima", "Ariya", "Frontier", "GT-R", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Titan", "Versa", "Z", "Qashqai", "Juke", "X-Trail"],
  "Pagani": ["Huayra", "Utopia", "Zonda"],
  "Peugeot": ["208", "2008", "308", "3008", "408", "508", "5008"],
  "Polestar": ["1", "2", "3", "4"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Ram": ["1500", "2500", "3500", "ProMaster"],
  "Renault": ["Clio", "Captur", "Megane", "Austral", "Arkana", "Zoe", "Twingo", "Scenic", "Espace"],
  "Rivian": ["R1S", "R1T"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Spectre"],
  "Seat": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  "Skoda": ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  "Smart": ["#1", "#3", "Fortwo"],
  "Subaru": ["Ascent", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "WRX"],
  "Suzuki": ["Swift", "Vitara", "Jimny", "S-Cross", "Ignis"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  "Toyota": ["4Runner", "Avalon", "Camry", "Corolla", "GR86", "GR Corolla", "GR Supra", "Highlander", "Land Cruiser", "Prius", "RAV4", "Sequoia", "Sienna", "Tacoma", "Tundra", "Venza", "Yaris", "Hilux", "CH-R"],
  "Volkswagen": ["Arteon", "Atlas", "Golf", "ID.4", "ID.Buzz", "Jetta", "Passat", "Taos", "Tiguan", "Touareg", "Polo", "T-Roc", "T-Cross"],
  "Volvo": ["C40", "EX30", "EX90", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"]
};

export const FUEL_TYPES = ["Gasoline", "Diesel", "Electric", "Hybrid", "Plug-in Hybrid", "LPG", "Hydrogen"];
export const GEARBOX_TYPES = ["Automatic", "Manual", "Semi-Automatic", "CVT"];
