import Navbar from '../components/Navbar'

export default function Terms() {
  return (
    <div className="min-h-screen bg-surface-low dark:bg-surface-low pt-32 pb-20 px-6">
      <Navbar />
      <div className="max-w-3xl mx-auto bg-surface dark:bg-surface-high/40 p-8 md:p-12 rounded-[32px] border border-overlay shadow-sm">
        <h1 className="text-3xl font-display font-bold text-on-surface mb-6">Terms of Service</h1>
        <p className="text-muted mb-4">Last updated: March 31, 2026</p>
        
        <div className="space-y-6 text-muted">
          <section>
            <h2 className="text-xl font-bold text-on-surface mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using carxai, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our service.</p>
          </section>
          
          <section>
            <h2 className="text-xl font-bold text-on-surface mb-3">2. Description of Service</h2>
            <p>carxai provides AI-powered automotive diagnostics and connection to nearby automotive service professionals. Diagnostic results are generated by artificial intelligence based on user input and photos, and should be verified by certified professionals before major mechanical repairs.</p>
          </section>
          
          <section>
            <h2 className="text-xl font-bold text-on-surface mb-3">3. Subscriptions and Payments</h2>
            <p>Some features require a paid subscription. You will be billed in advance on a recurring basis as per your subscription plan. You may cancel your subscription at any time.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-on-surface mb-3">4. Disclaimer of Warranties</h2>
            <p>Our service is provided "as is" and "as available" without any warranty or condition, express, implied or statutory. We do not guarantee that the AI diagnostics will be 100% accurate or suitable for your specific mechanical situation.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
